name: Deploy to Koyeb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Koyeb CLI
      run: |
        curl -fsSL https://get.koyeb.com | sh
        echo "$HOME/.koyeb/bin" >> $GITHUB_PATH
    
    - name: Deploy to Koyeb
      uses: koyeb/action-git-deploy@v1
      env:
        KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
      with:
        app-name: gball-server
        service-name: gball-server
        docker: |
          dockerfile: server/Dockerfile
          docker-build-args: |
            NODE_ENV=production
        service-env: |
          NODE_ENV=production
          PORT=8080